<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rnAppGenerator" nsURI="http://rnappgen" nsPrefix="rnAppGen">
  <eClassifiers xsi:type="ecore:EClass" name="MobileApp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigator" lowerBound="1"
        eType="#//Navigator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Navigator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//NavigatorType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedNavigators" upperBound="-1"
        eType="#//Navigator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screens" lowerBound="1"
        upperBound="-1" eType="#//Screen" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialScreen" lowerBound="1"
        eType="#//Screen"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NavigatorType">
    <eLiterals name="Stack"/>
    <eLiterals name="Tab"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Screen">
    <eOperations name="navigateTo"/>
    <eOperations name="goBackTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rnComponents" upperBound="-1"
        eType="#//RNComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nbComponents" upperBound="-1"
        eType="#//NBComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenState" eType="#//State"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scrollable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flexVerticalPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flexVerticalSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flexHorizontalPosition"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flexHorizontalSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="margin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="padding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verticalAlignment" eType="#//AlignmentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontalAlignment" eType="#//AlignmentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NBComponent" abstract="true" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="RNComponent" abstract="true" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialState" eType="#//JSObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JSObject" instanceTypeName="JSObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//RNComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//NBComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="theme" eType="#//ButtonTheme"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ButtonType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="#//ButtonSize"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//NBComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="2" upperBound="-1"
        eType="#//ListItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListItem" eSuperTypes="#//NBComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftIcon" eType="#//Icon"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightIcon" eType="#//Icon"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//NBComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputText" eSuperTypes="#//NBComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//InputType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ButtonTheme">
    <eLiterals name="primary"/>
    <eLiterals name="light"/>
    <eLiterals name="success"/>
    <eLiterals name="info"/>
    <eLiterals name="danger"/>
    <eLiterals name="warning"/>
    <eLiterals name="dark"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ButtonType">
    <eLiterals name="default"/>
    <eLiterals name="transparent"/>
    <eLiterals name="outline"/>
    <eLiterals name="rounded"/>
    <eLiterals name="block"/>
    <eLiterals name="full"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ButtonSize">
    <eLiterals name="regular"/>
    <eLiterals name="small"/>
    <eLiterals name="large"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Card" eSuperTypes="#//NBComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Icon" eSuperTypes="#//NBComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InputType">
    <eLiterals name="regular"/>
    <eLiterals name="rounded"/>
    <eLiterals name="underlined"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlignmentType">
    <eLiterals name="center"/>
    <eLiterals name="flexStart"/>
    <eLiterals name="flexEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoginForm" eSuperTypes="#//NBComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userPlaceholder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passwordPlaceholder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buttonTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Picker" eSuperTypes="#//NBComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeHolder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RadioButton" eSuperTypes="#//NBComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
